feat:Escape '$' variable from secrets content
adobe/aio-cli-plugin-api-mesh pull request #155
Opened 2024-07-22 15:39 UTC by romario-0

Escape '$' variable from secrets content

## Description

We have introduced a escape character "\" for escaping "$" variable from secret content. The code introduces a temporary randomly generated placeholder in place of the "$" variable that is preceded by "\" symbol and after the parsing of secret content, it replaces back the original string in place of the placeholder. Thus escaping the variable from being parsed.

## Motivation and Context

Earlier we couldn't add "$" with text as string, this used to get parsed and if the value is not found then blank space was replaced for that string. To enable adding of such strings this code is added.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-07-23 09:40 UTC, romario-0 commented
Reopening with signed CLA

2024-07-24 03:16 UTC, revanth0212 requested changes
Nice work @romario-0 

Left a quick suggestion. Also, please consider adding a positive and negative unit test covering your changes.

2024-07-24 03:16 UTC, revanth0212 commented on src/utils.js
> +	return [newContent, placeholderMap];
My suggestion, dont make it an array. Return an object instead.

```suggestion
	return {
	    secrets: newContent,
	    placeholderMap
	};
```

2024-07-24 15:25 UTC, revanth0212 approved these changes

2024-07-24 15:52 UTC, jward-magento approved these changes

2024-07-24 20:06 UTC, merged