feat(legacy): CEXT-3832 - remove legacy mesh references
adobe/aio-cli-plugin-api-mesh pull request #190
Opened 2024-11-19 07:57 UTC by amolina-adobe

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-11-19 15:51 UTC, jhadobe requested changes

2024-11-19 15:51 UTC, jhadobe commented on src/commands/api-mesh/status.js
> +				`Unable to get the mesh status. If the error persists please contact support. RequestId: ${global.requestId}`,
```suggestion
				`Unable to get mesh status. If this error persists, contact support. RequestId: ${global.requestId}`,
```

2024-11-19 15:51 UTC, jhadobe commented on src/commands/api-mesh/status.js
> +				this.log('Mesh status is not available. Please wait for a while and try again.');
```suggestion
				this.log('Mesh status is not available. Wait a few minutes and try again.');
```

2024-11-19 15:51 UTC, jhadobe commented on src/commands/api-mesh/status.js
> +					`Mesh is currently being provisioned. Please wait a few minutes before checking again.`,
```suggestion
					`Currently provisioning your mesh. Wait a few minutes and check again.`,
```

2024-11-19 15:51 UTC, jhadobe commented on src/commands/api-mesh/status.js
> +					`Mesh is currently being de-provisioned. Please wait a few minutes before checking again.`,
```suggestion
					`Currently de-provisioning your mesh. Wait a few minutes and check again.`,
```

2024-11-19 15:51 UTC, jhadobe commented on src/commands/api-mesh/status.js
> +				this.log(`Mesh has been successfully built.`);
```suggestion
				this.log(`Mesh was built successfully.`);
```

2024-11-19 15:51 UTC, jhadobe commented on src/commands/api-mesh/status.js
> +				this.log('Mesh status is not available. Please wait for a while and try again.');
```suggestion
				this.log('Mesh status is not available. Wait a few minutes and try again.');
```

2024-11-25 21:38 UTC, amolina-adobe commented on src/lib/devConsole.js
> -			status: 'ERROR',
The `error` status has special meaning in the deployments table. It signifies that an error occurred during provisioning. 

However, an error here signifies that we were unable to fetch the deployment status altogether. Thus, we don't want to default to that status here. Changed to `null` instead

2024-11-26 15:22 UTC, revanth0212 submitted a review, later dismissed

2024-11-26 15:45 UTC, kmaschi approved these changes

2024-11-26 15:58 UTC, kmaschi approved these changes

2024-11-26 16:16 UTC, revanth0212 approved these changes

2024-11-26 16:19 UTC, merged