Test api cred
adobe/aio-cli-plugin-api-mesh pull request #83
Opened 2023-08-24 01:53 UTC by dthampy

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-24 22:10 UTC, amolina-adobe requested changes

2023-08-24 22:10 UTC, amolina-adobe commented on src/commands/api-mesh/__tests__/create.test.js
>  		]
Can we just delete this?

2023-08-24 22:10 UTC, amolina-adobe commented on src/commands/api-mesh/__tests__/create.test.js
> +	`);*/
This too.

2023-08-25 13:46 UTC, dthampy commented on src/lib/devConsole.js
> +			if (credential) {
Done

2023-08-25 13:46 UTC, dthampy commented on src/lib/devConsole.js
> +				logger.error('API Key credential not found on workspace');
Done

2023-08-25 13:46 UTC, dthampy commented on src/commands/api-mesh/__tests__/create.test.js
>  		]
Done

2023-08-25 13:46 UTC, dthampy commented on src/commands/api-mesh/__tests__/create.test.js
> +	`);*/
Done

2023-08-25 17:14 UTC, amolina-adobe approved these changes

2023-08-25 18:23 UTC, jward-magento approved these changes
I confirmed that the creation of the new key works when the workspace does not have a pre-existling key.

2023-08-29 14:33 UTC, brasewel submitted a review, later dismissed

2023-08-30 14:58 UTC, jward-magento submitted a review, later dismissed

2023-08-30 16:38 UTC, jward-magento reviewed
Should this be rev'd all the way to 3.3.3 or should it be like 3.0.1?

2023-08-30 16:42 UTC, dthampy commented
> Should this be rev'd all the way to 3.3.3 or should it be like 3.0.1?

Good call @jward-magento
I believe 3.0.0 should be good
@revanth0212 , do you agree?

2023-08-30 17:24 UTC, amolina-adobe approved these changes

2023-08-30 17:41 UTC, brasewel approved these changes

2023-08-30 18:31 UTC, revanth0212 approved these changes

2023-08-30 18:36 UTC, merged