Feature/run command select arg
adobe/aio-cli-plugin-api-mesh pull request #98
Opened 2023-11-02 18:10 UTC by simrangulati

## Summary 

To add select flag within the run command to run the local mesh server using the existing mesh artifact.

## Description

The current run command is used to run the local development server by validating, building, and compiling the mesh artifacts for a particular mesh configuration.

With the use of a select flag, the user can log in to a particular workspace and run the local development server using the existing mesh artifact.

![Screenshot (98)](https://github.com/adobe/aio-cli-plugin-api-mesh/assets/13031249/1e908dc1-eb73-4983-a4d8-6c806dde74b4)

## Related Issue

https://jira.corp.adobe.com/browse/CEXT-2082

## Motivation and Context

To allow the user to use the use existing artifact and run over the local server.

## How Has This Been Tested?

### Updated unit tests

![image](https://github.com/adobe/aio-cli-plugin-api-mesh/assets/13031249/6d820fe7-1c83-4ca3-b48d-ff605eff7625)

### Testing using `aio api-mesh run --select` inside the package

![image](https://github.com/adobe/aio-cli-plugin-api-mesh/assets/13031249/508acf61-3328-42c9-a8c3-5e2226a922e1)

![image](https://github.com/adobe/aio-cli-plugin-api-mesh/assets/13031249/2fb49ee6-65fc-4392-91ec-3158858a7231)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-11-08 17:07 UTC, revanth0212 submitted a review, later dismissed

2023-11-10 01:32 UTC, amolina-adobe submitted a review, later dismissed

2023-11-10 16:18 UTC, jhadobe requested changes

2023-11-10 16:18 UTC, jhadobe commented on src/commands/api-mesh/run.js
> +							`Unable to get mesh artifact. Please check the details and try again. RequestId: ${global.requestId}`,
Are we going to use the term "artifact" in the docs? I think we could refer to them as "previously created meshes":

```suggestion
							`Unable to find previously created mesh. Please check the details and try again. RequestId: ${global.requestId}`,
```

2023-11-10 16:18 UTC, jhadobe commented on src/commands/api-mesh/run.js
> +					this.log('The setup of mesh files for downloaded artifact is complete');
```suggestion
					this.log('Successfully downloaded previously created mesh');
```

2023-11-10 16:18 UTC, jhadobe commented on src/commands/api-mesh/run.js
> +						throw new Error('Mesh files setup for downloaded artifact has failed');
```suggestion
						throw new Error('Failed to install downloaded mesh');
```

2023-11-14 04:40 UTC, revanth0212 submitted a review, later dismissed

2023-11-14 15:52 UTC, amolina-adobe approved these changes

2023-11-14 15:54 UTC, revanth0212 approved these changes

2023-11-14 15:55 UTC, merged